version: '3.8'

services:
  mlapp:
    container_name: app_container
    image: app_docker
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BACKEND_URI: sqlite:///mlflow.db
      ARTIFACT_ROOT: artifacts

